export default function ColorCircle({ color }: { color: string }) {
    const diccionarioColores: { [key: string]: string } = {
        "amarillo": "#FFFF00",
        "amarillo claro": "#FFFACD",
        "amarillo oscuro": "#FFD700",
        "ámbar": "#FFBF00",
        "arena": "#C2B280",
        "azul": "#0000FF",
        "azul claro": "#ADD8E6",
        "azul oscuro": "#00008B",
        "azul marino": "#001F3F",
        "azul celeste": "#87CEEB",
        "azul cielo": "#87CEFA",
        "azul pastel": "#A7C7E7",
        "azul turquesa": "#40E0D0",
        "beige": "#F5F5DC",
        "blanco": "#FFFFFF",
        "bordó": "#800020",
        "bronce": "#CD7F32",
        "café": "#6F4E37",
        "caqui": "#C3B091",
        "celeste": "#87CEEB",
        "champán": "#F7E7CE",
        "chocolate": "#7B3F00",
        "cian": "#00FFFF",
        "coral": "#FF7F50",
        "crema": "#FFFDD0",
        "dorado": "#FFD700",
        "fucsia": "#FF00FF",
        "granate": "#800000",
        "gris": "#808080",
        "gris claro": "#D3D3D3",
        "gris oscuro": "#2F4F4F",
        "gris perla": "#C0C0C0",
        "guinda": "#8B0000",
        "lavanda": "#E6E6FA",
        "lila": "#C8A2C8",
        "magenta": "#FF00FF",
        "malva": "#B57EDC",
        "marfil": "#FFFFF0",
        "marrón": "#8B4513",
        "melocotón": "#FFDAB9",
        "menta": "#98FF98",
        "mostaza": "#FFDB58",
        "naranja": "#FFA500",
        "naranja oscuro": "#FF8C00",
        "negro": "#000000",
        "ocre": "#CC7722",
        "oro": "#DAA520",
        "púrpura": "#800080",
        "plata": "#C0C0C0",
        "rojo": "#FF0000",
        "rojo oscuro": "#8B0000",
        "rojo vino": "#722F37",
        "rosa": "#FFC0CB",
        "rosa claro": "#FFB6C1",
        "rosa fuerte": "#FF69B4",
        "salmon": "#FA8072",
        "salmon claro": "#FFA07A",
        "terracota": "#E2725B",
        "turquesa": "#40E0D0",
        "verde": "#00FF00",
        "verde claro": "#90EE90",
        "verde oscuro": "#006400",
        "verde lima": "#32CD32",
        "verde menta": "#98FB98",
        "verde oliva": "#808000",
        "verde agua": "#00FA9A",
        "verde noche": "#013220",
        "vino": "#8B0000",
        "violeta": "#8A2BE2",
        "azul pacífico": "#5F9EA0",
        "verde alpino": "#0B6623",
        "azul sierra": "#4682B4",
        "titanio natural": "#B0B0B0",
        "gris titanio": "#4B4B4B",
    };

    const colorKey = color.trim().toLowerCase();
    const colorHex = diccionarioColores[colorKey] || "#CCCCCC";

    return (
        <div
            className="w-4 h-4 rounded-full shadow-lg border border-gray-200 hover:scale-105 transition-transform duration-150"
            title={color}
            style={{
                backgroundColor: colorHex,
            }}
        />
    );
}
