//File: frontend/src/schemas/sale.schema.ts

import { z } from "zod";

/**
 * ENUMS
 * Synchronized with Backend Mongoose Model
 */
export const SaleStatusEnum = z.enum([
    'QUOTE',
    'PENDING',
    'COMPLETED',
    'PARTIALLY_REFUNDED',
    'REFUNDED',
    'CANCELED',
]);

export const PaymentMethodEnum = z.enum([
    'CASH',
    'CARD',
    'YAPE',
    'PLIN',
    'TRANSFER',
]);

export const PaymentStatusEnum = z.enum([
    'pending',
    'approved',
    'rejected',
    'refunded',
]);

export const ReceiptTypeEnum = z.enum(['TICKET', 'BOLETA', 'FACTURA']);

export const DeliveryMethodEnum = z.enum(['PICKUP', 'DELIVERY']);

export const DocumentTypeEnum = z.enum(['DNI', 'RUC', 'CE']);

/**
 * SHARED HELPERS
 * Handles MongoDB Population (ID string OR Populated Object)
 */
const populatedField = z.union([
    z.string(),
    z.object({
        _id: z.string(),
        nombre: z.string().optional(),
        email: z.string().optional(),
    }).passthrough()
]);

/**
 * SUB-SCHEMAS
 */

export const customerSnapshotSchema = z.object({
    nombre: z.string().optional(),
    tipoDocumento: DocumentTypeEnum.optional(),
    numeroDocumento: z.string().optional(),
    telefono: z.string().optional(),
    email: z.string().email().optional().or(z.literal('')),
    direccion: z.string().optional(),
});

export const saleItemSchema = z.object({
    product: populatedField,
    variantId: z.string().optional(),
    quantity: z.number().min(1, "Quantity must be at least 1"),
    price: z.number().min(0, "Price cannot be negative"),
    discount: z.number().default(0),
    cost: z.number().default(0), // Crucial for profit reporting
});

export const statusHistorySchema = z.object({
    status: SaleStatusEnum,
    changedAt: z.coerce.date(),
});

/**
 * MAIN SALE SCHEMA
 */
export const saleSchema = z.object({
    _id: z.string().optional(),

    // Relations
    customer: populatedField.optional().nullable(),
    customerSnapshot: customerSnapshotSchema.optional(),
    employee: populatedField,
    cashShiftId: z.union([z.string(), z.object({ _id: z.string() }).passthrough()]),

    // Items
    items: z.array(saleItemSchema).min(1, "The sale must contain at least one item"),

    // Financials
    subtotal: z.number().min(0),
    totalDiscountAmount: z.number().default(0),
    totalSurchargeAmount: z.number().default(0),
    totalPrice: z.number().min(0),

    // Identity
    receiptType: ReceiptTypeEnum.default('TICKET'),
    receiptNumber: z.string().optional(), // Generated by backend

    // State
    status: SaleStatusEnum.default('COMPLETED'),
    statusHistory: z.array(statusHistorySchema).default([]),

    // Payment
    paymentMethod: PaymentMethodEnum.default('CASH'),
    paymentStatus: PaymentStatusEnum.default('approved'),
    paymentId: z.string().optional(),

    // Logistics
    storeLocation: z.string().optional(),
    deliveryMethod: DeliveryMethodEnum.default('PICKUP'),

    // Proforma / Quote Logic
    isQuote: z.boolean().default(false),
    quoteExpirationDate: z.coerce.date().optional(),

    // Timestamps (Coerced from ISO String to Date object)
    createdAt: z.coerce.date().optional(),
    updatedAt: z.coerce.date().optional(),
});

/**
 * SPECIFIC SCHEMAS FOR ACTIONS
 */

// Use this for the POST /api/sales/v2 payload
export const createSaleSchema = saleSchema.omit({
    _id: true,
    receiptNumber: true,
    statusHistory: true,
    createdAt: true,
    updatedAt: true,
}).extend({
    // Ensure IDs are sent as strings during creation
    customer: z.string().optional(),
    employee: z.string(),
    cashShiftId: z.string(),
    items: z.array(z.object({
        product: z.string(),
        variantId: z.string().optional(),
        quantity: z.number().min(1),
        price: z.number(),
        discount: z.number().optional(),
        cost: z.number(),
    })),
});

/**
 * TYPES
 */
export type Sale = z.infer<typeof saleSchema>;
export type SaleItem = z.infer<typeof saleItemSchema>;
export type CreateSalePayload = z.infer<typeof createSaleSchema>;
export type CustomerSnapshot = z.infer<typeof customerSnapshotSchema>;